### ISSUE TITLE
Firecracker codegen crash: pointee type assertion

### ISSUE THREAD

**Issue by avanhatt** [model-checking/rmc#272]
The Firecracker demo fails a newly-added assertion that the regression tests all pass:

```rust
thread 'rustc' panicked at 'assertion failed: pointee_type(src_mir_type).map_or(true, |p| self.use_thin_pointer(p))', compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:682:13
stack backtrace:
   0: rust_begin_unwind
             at /home/runner/work/rmc/rmc/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /home/runner/work/rmc/rmc/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /home/runner/work/rmc/rmc/library/core/src/panicking.rs:50:5
   3: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::cast_to_unsized_expr
             at /home/runner/work/rmc/rmc/compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:682:13
   4: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_pointer_cast
             at /home/runner/work/rmc/rmc/compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:660:17
   5: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_rvalue
             at /home/runner/work/rmc/rmc/compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:391:17
   6: rustc_codegen_llvm::gotoc::statement::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_statement
             at /home/runner/work/rmc/rmc/compiler/rustc_codegen_llvm/src/gotoc/statement.rs:437:60
   7: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_block
             at /home/runner/work/rmc/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:60:32
   8: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:145:71
   9: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/runner/work/rmc/rmc/library/core/src/iter/traits/iterator.rs:733:29
  10: core::iter::adapters::map::map_fold::{{closure}}
             at /home/runner/work/rmc/rmc/library/core/src/iter/adapters/map.rs:82:21
  11: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /home/runner/work/rmc/rmc/library/core/src/iter/adapters/enumerate.rs:104:27
  12: core::iter::traits::iterator::Iterator::fold
             at /home/runner/work/rmc/rmc/library/core/src/iter/traits/iterator.rs:2153:21
  13: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /home/runner/work/rmc/rmc/library/core/src/iter/adapters/enumerate.rs:110:9
  14: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/runner/work/rmc/rmc/library/core/src/iter/adapters/map.rs:122:9
  15: core::iter::traits::iterator::Iterator::for_each
             at /home/runner/work/rmc/rmc/library/core/src/iter/traits/iterator.rs:736:9
  16: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function
             at /home/runner/work/rmc/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:145:13
  17: <rustc_codegen_llvm::gotoc::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /home/runner/work/rmc/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:316:47
  18: rustc_interface::passes::start_codegen::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/passes.rs:1060:9
  19: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /home/runner/work/rmc/rmc/compiler/rustc_data_structures/src/profiling.rs:573:9
  20: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /home/runner/work/rmc/rmc/compiler/rustc_session/src/utils.rs:16:9
  21: rustc_interface::passes::start_codegen
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/passes.rs:1059:19
  22: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/queries.rs:295:20
  23: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/passes.rs:799:42
  24: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_middle/src/ty/context.rs:1744:50
  25: rustc_middle::ty::context::tls::set_tlv
             at /home/runner/work/rmc/rmc/compiler/rustc_middle/src/ty/context.rs:1728:9
  26: rustc_middle::ty::context::tls::enter_context
             at /home/runner/work/rmc/rmc/compiler/rustc_middle/src/ty/context.rs:1744:9
  27: rustc_interface::passes::QueryContext::enter
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/passes.rs:799:9
  28: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/queries.rs:286:13
  29: rustc_interface::queries::Query<T>::compute
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/queries.rs:40:28
  30: rustc_interface::queries::Queries::ongoing_codegen
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/queries.rs:284:9
  31: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_driver/src/lib.rs:414:13
  32: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/queries.rs:435:19
  33: rustc_driver::run_compiler::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_driver/src/lib.rs:313:22
  34: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/interface.rs:208:13
  35: rustc_span::with_source_map
             at /home/runner/work/rmc/rmc/compiler/rustc_span/src/lib.rs:873:5
  36: rustc_interface::interface::create_compiler_and_run
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/interface.rs:202:5
  37: rustc_interface::interface::run_compiler::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/interface.rs:224:12
  38: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/util.rs:158:13
  39: scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  40: rustc_span::with_session_globals
             at /home/runner/work/rmc/rmc/compiler/rustc_span/src/lib.rs:104:5
  41: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/util.rs:156:9
  42: rustc_interface::util::scoped_thread::{{closure}}
             at /home/runner/work/rmc/rmc/compiler/rustc_interface/src/util.rs:131:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by avanhatt** [comment]
The type in question:
```rust
&std::sync::Mutex<dyn bus::BusDevice>
```
