### ISSUE TITLE
RMC crash on fat pointer comparison

### ISSUE THREAD

**Issue by avanhatt** [model-checking/rmc#327]
RMC crashes on the following core Rust test (``)

```rust
// run-pass
// check raw fat pointer ops

use std::mem;

fn assert_inorder<T: PartialEq + PartialOrd>(a: &[T]) {
    for i in 0..a.len() {
        for j in 0..a.len() {
            if i < j {
                assert!(a[i] < a[j]);
                assert!(a[i] <= a[j]);
                assert!(!(a[i] == a[j]));
                assert!(a[i] != a[j]);
                assert!(!(a[i] >= a[j]));
                assert!(!(a[i] > a[j]));
            } else if i == j {
                assert!(!(a[i] < a[j]));
                assert!(a[i] <= a[j]);
                assert!(a[i] == a[j]);
                assert!(!(a[i] != a[j]));
                assert!(a[i] >= a[j]);
                assert!(!(a[i] > a[j]));
            } else {
                assert!(!(a[i] < a[j]));
                assert!(!(a[i] <= a[j]));
                assert!(!(a[i] == a[j]));
                assert!(a[i] != a[j]);
                assert!(a[i] >= a[j]);
                assert!(a[i] > a[j]);
            }
        }
    }
}

trait Foo { fn foo(&self) -> usize; }
impl<T> Foo for T {
    fn foo(&self) -> usize {
        mem::size_of::<T>()
    }
}

struct S<T:?Sized>(u32, T);

fn main() {
    let mut array = [0,1,2,3,4];
    let mut array2 = [5,6,7,8,9];

    // fat ptr comparison: addr then extra

    // check ordering for arrays
    let mut ptrs: Vec<*const [u8]> = vec![
        &array[0..0], &array[0..1], &array, &array[1..]
    ];

    let array_addr = &array as *const [u8] as *const u8 as usize;
    let array2_addr = &array2 as *const [u8] as *const u8 as usize;
    if array2_addr < array_addr {
        ptrs.insert(0, &array2);
    } else {
        ptrs.push(&array2);
    }
    assert_inorder(&ptrs);

    // check ordering for mut arrays
    let mut ptrs: Vec<*mut [u8]> = vec![
        &mut array[0..0], &mut array[0..1], &mut array, &mut array[1..]
    ];

    let array_addr = &mut array as *mut [u8] as *mut u8 as usize;
    let array2_addr = &mut array2 as *mut [u8] as *mut u8 as usize;
    if array2_addr < array_addr {
        ptrs.insert(0, &mut array2);
    } else {
        ptrs.push(&mut array2);
    }
    assert_inorder(&ptrs);

    let mut u8_ = (0u8, 1u8);
    let mut u32_ = (4u32, 5u32);

    // check ordering for ptrs
    let buf: &mut [*const dyn Foo] = &mut [
        &u8_, &u8_.0,
        &u32_, &u32_.0,
    ];
    buf.sort_by(|u,v| {
        let u : [*const (); 2] = unsafe { mem::transmute(*u) };
        let v : [*const (); 2] = unsafe { mem::transmute(*v) };
        u.cmp(&v)
    });
    assert_inorder(buf);

    // check ordering for mut ptrs
    let buf: &mut [*mut dyn Foo] = &mut [
        &mut u8_, &mut u8_.0,
        &mut u32_, &mut u32_.0,
    ];
    buf.sort_by(|u,v| {
        let u : [*const (); 2] = unsafe { mem::transmute(*u) };
        let v : [*const (); 2] = unsafe { mem::transmute(*v) };
        u.cmp(&v)
    });
    assert_inorder(buf);

    // check ordering for structs containing arrays
    let ss: (S<[u8; 2]>,
             S<[u8; 3]>,
             S<[u8; 2]>) = (
        S(7, [8, 9]),
        S(10, [11, 12, 13]),
        S(4, [5, 6])
    );
    assert_inorder(&[
        &ss.0 as *const S<[u8]>,
        &ss.1 as *const S<[u8]>,
        &ss.2 as *const S<[u8]>
    ]);
}
```

```rust
thread 'rustc' panicked at 'BinaryOperation Expression does not typecheck Equal Expr { value: Symbol { identifier: "_RNvXs0_NtNtCsgWci0eQkB8o_4core3ptr7mut_ptrODNtCsihSqj1NPF93_11raw_fat_ptr3FooEL_NtNtB9_3cmp9PartialEq2eqBI_::1::var_3" }, typ: StructTag("tag-dyn Foo"), location: None } Expr { value: Symbol { identifier: "_RNvXs0_NtNtCsgWci0eQkB8o_4core3ptr7mut_ptrODNtCsihSqj1NPF93_11raw_fat_ptr3FooEL_NtNtB9_3cmp9PartialEq2eqBI_::1::var_4" }, typ: StructTag("tag-dyn Foo"), location: None }', compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:824:9
```

<details>
<summary>
stack backtrace:
</summary>
```rust
   0: rust_begin_unwind
             at ./library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at ./library/std/src/panicking.rs:457:5
   2: rustc_codegen_llvm::gotoc::cbmc::goto_program::expr::Expr::binop
             at ./compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:824:9
   3: rustc_codegen_llvm::gotoc::cbmc::goto_program::expr::Expr::eq
             at ./compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:946:9
   4: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_comparison
             at ./compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:26:21
   5: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_rvalue_binary_op
             at ./compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:325:17
   6: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_rvalue
             at ./compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:393:59
   7: rustc_codegen_llvm::gotoc::statement::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_statement
             at ./compiler/rustc_codegen_llvm/src/gotoc/statement.rs:458:33
   8: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_block
             at ./compiler/rustc_codegen_llvm/src/gotoc/mod.rs:123:32
   9: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function::{{closure}}
             at ./compiler/rustc_codegen_llvm/src/gotoc/mod.rs:206:71
  10: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at ./library/core/src/iter/traits/iterator.rs:733:29
  11: core::iter::adapters::map::map_fold::{{closure}}
             at ./library/core/src/iter/adapters/map.rs:82:21
  12: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at ./library/core/src/iter/adapters/enumerate.rs:104:27
  13: core::iter::traits::iterator::Iterator::fold
             at ./library/core/src/iter/traits/iterator.rs:2173:21
  14: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at ./library/core/src/iter/adapters/enumerate.rs:110:9
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at ./library/core/src/iter/adapters/map.rs:122:9
  16: core::iter::traits::iterator::Iterator::for_each
             at ./library/core/src/iter/traits/iterator.rs:736:9
  17: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function
             at ./compiler/rustc_codegen_llvm/src/gotoc/mod.rs:206:13
  18: <rustc_codegen_llvm::gotoc::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{{closure}}
             at ./compiler/rustc_codegen_llvm/src/gotoc/mod.rs:392:35
  19: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::call_with_panic_debug_info::{{closure}}
             at ./compiler/rustc_codegen_llvm/src/gotoc/mod.rs:102:13
  20: std::thread::local::LocalKey<T>::try_with
             at ./library/std/src/thread/local.rs:399:16
  21: std::thread::local::LocalKey<T>::with
             at ./library/std/src/thread/local.rs:375:9
  22: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::call_with_panic_debug_info
             at ./compiler/rustc_codegen_llvm/src/gotoc/mod.rs:100:9
  23: <rustc_codegen_llvm::gotoc::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at ./compiler/rustc_codegen_llvm/src/gotoc/mod.rs:391:25
  24: rustc_interface::passes::start_codegen::{{closure}}
             at ./compiler/rustc_interface/src/passes.rs:1058:9
  25: rustc_data_structures::profiling::VerboseTimingGuard::run
             at ./compiler/rustc_data_structures/src/profiling.rs:573:9
  26: rustc_session::utils::<impl rustc_session::session::Session>::time
             at ./compiler/rustc_session/src/utils.rs:16:9
  27: rustc_interface::passes::start_codegen
             at ./compiler/rustc_interface/src/passes.rs:1057:19
  28: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}::{{closure}}
             at ./compiler/rustc_interface/src/queries.rs:254:20
  29: rustc_interface::passes::QueryContext::enter::{{closure}}
             at ./compiler/rustc_interface/src/passes.rs:780:42
  30: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at ./compiler/rustc_middle/src/ty/context.rs:1765:50
  31: rustc_middle::ty::context::tls::set_tlv
             at ./compiler/rustc_middle/src/ty/context.rs:1749:9
  32: rustc_middle::ty::context::tls::enter_context
             at ./compiler/rustc_middle/src/ty/context.rs:1765:9
  33: rustc_interface::passes::QueryContext::enter
             at ./compiler/rustc_interface/src/passes.rs:780:9
  34: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}
             at ./compiler/rustc_interface/src/queries.rs:245:13
  35: rustc_interface::queries::Query<T>::compute
             at ./compiler/rustc_interface/src/queries.rs:38:28
  36: rustc_interface::queries::Queries::ongoing_codegen
             at ./compiler/rustc_interface/src/queries.rs:243:9
  37: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at ./compiler/rustc_driver/src/lib.rs:407:13
  38: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at ./compiler/rustc_interface/src/queries.rs:394:19
  39: rustc_driver::run_compiler::{{closure}}
             at ./compiler/rustc_driver/src/lib.rs:312:22
  40: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at ./compiler/rustc_interface/src/interface.rs:208:13
  41: rustc_span::with_source_map
             at ./compiler/rustc_span/src/lib.rs:917:5
  42: rustc_interface::interface::create_compiler_and_run
             at ./compiler/rustc_interface/src/interface.rs:202:5
  43: rustc_interface::interface::run_compiler::{{closure}}
             at ./compiler/rustc_interface/src/interface.rs:224:12
  44: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at ./compiler/rustc_interface/src/util.rs:155:13
  45: scoped_tls::ScopedKey<T>::set
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  46: rustc_span::create_session_globals_then
             at ./compiler/rustc_span/src/lib.rs:108:5
  47: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at ./compiler/rustc_interface/src/util.rs:153:9
  48: rustc_interface::util::scoped_thread::{{closure}}
             at ./compiler/rustc_interface/src/util.rs:128:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic
```
</details>

**Comment by celinval** [comment]
Note to myself: We need to compare the data field and, potentially, the metadata. Need to double check the latter.

**Comment by celinval** [comment]
https://doc.rust-lang.org/std/ptr/fn.eq.html

**Comment by celinval** [comment]
Lowering the priority since this has been mitigated.

**Comment by celinval** [comment]
I'm looking into this issue right now, but it is still not clear to me what the actual semantics of pointer comparison is for Rust. Even for thin pointers it isn't clear.

Interesting enough, the standard library does support Eq and Ord of raw pointers and the compiler behavior is somewhat deterministic (not clear if the LLVM portion is though).  I'll keep digging.

Here are some interesting references:

- https://github.com/rust-lang/unsafe-code-guidelines/issues/239
- https://github.com/rust-lang/rfcs/pull/1135
- https://rust-lang.github.io/rfcs/1135-raw-pointer-comparisons.html

**Comment by celinval** [comment]
From [this discussion in the zulip tlang channel](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Semantics.20of.20raw.20pointer.20comparison), it seems that pointers with the same provenance, we should be able to do the following:
- Compare concrete address for data pointers and thin pointers.
- Compare metadata for fat pointers (i.e.: length or vtable pointer).

However, the vtable pointer has a few caveats.
1. It will only have the same provenance if they point to the same vtable.
2. In theory, vtable may have different addresses even if they represent the same type. That may happen when each pointer is created in a different compilation units ([see this issue for more details](https://github.com/rust-lang/rust/issues/69757)).

So I propose the following solution.
1. For now, we add support to fat pointers that represent slice and fail for vtable pointers.
2. We create an issue to implement vtable pointer comparison but only implement that if there is a real need, since this operation is not stable, users should probably avoid them.
   . If we do want to implement vtable comparison, we should use their concrete address and add non-determinism via uninterpreted functions (See http://www.cprover.org/cprover-manual/modeling/nondeterminism/).

We should also defer implementing comparison between pointers with different provenance. This behavior is also not well defined.
