### ISSUE TITLE
Panic in compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/rmc#533]
I tried the following:

1. `cargo new --lib foo`
2. Add `serde` as a dependency in `Cargo.toml`:
```
[dependencies]
serde = "1.0.130"
```
3. Run:
```
RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo build
```

with RMC version: `72d7cd412439460a7bc0ad0a2d483424377dbb4d`

```
$ RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo build
    Updating crates.io index
   Compiling serde v1.0.130
thread 'rustc' panicked at 'removal index (is 0) should be < len (is 0)', compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs:306:64
stack backtrace:
   0: rust_begin_unwind
             at /home/ubuntu/tools/rmc/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /home/ubuntu/tools/rmc/library/core/src/panicking.rs:103:14
   2: alloc::vec::Vec<T,A>::remove::assert_failed
             at /home/ubuntu/tools/rmc/library/alloc/src/vec/mod.rs:1390:13
   3: alloc::vec::Vec<T,A>::remove
             at /home/ubuntu/tools/rmc/library/alloc/src/vec/mod.rs:1395:13
   4: rustc_codegen_rmc::codegen::intrinsic::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_intrinsic
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs:306:58
   5: <rustc_codegen_rmc::overrides::hooks::Intrinsic as rustc_codegen_rmc::overrides::hooks::GotocHook>::handle
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/overrides/hooks.rs:266:21
   6: rustc_codegen_rmc::codegen::statement::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_funcall
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/statement.rs:330:28
   7: rustc_codegen_rmc::codegen::statement::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_terminator
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/statement.rs:65:17
   8: rustc_codegen_rmc::codegen::block::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_block
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/block.rs:30:28
   9: rustc_codegen_rmc::codegen::function::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:99:71
  10: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:724:29
  11: core::iter::adapters::map::map_fold::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/map.rs:84:21
  12: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/enumerate.rs:106:27
  13: core::iter::traits::iterator::Iterator::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:2164:21
  14: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/enumerate.rs:112:9
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/map.rs:124:9
  16: core::iter::traits::iterator::Iterator::for_each
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:727:9
  17: rustc_codegen_rmc::codegen::function::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:99:13
  18: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:99:35
  19: rustc_codegen_rmc::utils::debug::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:87:13
  20: std::thread::local::LocalKey<T>::try_with
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:399:16
  21: std::thread::local::LocalKey<T>::with
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:375:9
  22: rustc_codegen_rmc::utils::debug::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:84:9
  23: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:98:25
  24: rustc_interface::passes::start_codegen::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1052:9
  25: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /home/ubuntu/tools/rmc/compiler/rustc_data_structures/src/profiling.rs:611:9
  26: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /home/ubuntu/tools/rmc/compiler/rustc_session/src/utils.rs:16:9
  27: rustc_interface::passes::start_codegen
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1051:19
  28: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:254:20
  29: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:778:42
  30: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1771:50
  31: rustc_middle::ty::context::tls::set_tlv
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1755:9
  32: rustc_middle::ty::context::tls::enter_context
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1771:9
  33: rustc_interface::passes::QueryContext::enter
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:778:9
  34: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:245:13
  35: rustc_interface::queries::Query<T>::compute
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:38:28
  36: rustc_interface::queries::Queries::ongoing_codegen
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:243:9
  37: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:407:13
  38: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:394:19
  39: rustc_driver::run_compiler::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:312:22
  40: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:209:13
  41: rustc_span::with_source_map
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:956:5
  42: rustc_interface::interface::create_compiler_and_run
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:203:5
  43: rustc_interface::interface::run_compiler::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:225:12
  44: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:157:13
  45: scoped_tls::ScopedKey<T>::set
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  46: rustc_span::create_session_globals_then
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:106:5
  47: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:155:9
  48: rustc_interface::util::scoped_thread::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:130:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z trim-diagnostic-paths=no -Z codegen-backend=gotoc -C embed-bitcode=no -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

[RMC] current codegen item: codegen_function: std::hint::black_box
_ZN4core4hint9black_box17hb5f5c956dd7b461fE
[RMC] current codegen location: Loc { file: "/home/ubuntu/tools/rmc/library/core/src/hint.rs", function: None, line: 157, col: Some(1) }

RMC unexpectedly panicked during code generation.

If you are seeing this message, please file an issue here instead of on the Rust compiler: https://github.com/model-checking/rmc/issues/new?labels=bug&template=bug_report.md
error: could not compile `serde`

To learn more, run the command again with --verbose.
```
Interestingly, adding `--target x86_64-unknown-linux-gnu` to the `cargo build` arguments fixes the issue.

**Comment by zhassan-aws** [comment]
Bumped up the priority of this bug, since I'm running into it very frequently. Now, the example above panics whether `--target x86_64-unknown-linux-gnu` is passed to `cargo build` or not. Also, adding:
```
rand = "0.8.4"
```
instead of `serde` in the dependencies panics.
