### ISSUE TITLE
Compiling a simple example using cargo test panics

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/rmc#586]
Using `cargo test` instead of `cargo build` for compiling a simple example panics in `compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs`.

Steps to reproduce:
1. `cargo new --lib foo`
2. `cd foo`
3. `RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo test --target x86_64-unknown-linux-gnu -j1`

with RMC version: `02a830b8734`

```
thread 'rustc' panicked at 'removal index (is 0) should be < len (is 0)', compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs:306:64
stack backtrace:
   0: rust_begin_unwind
             at /home/ubuntu/tools/rmc/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /home/ubuntu/tools/rmc/library/core/src/panicking.rs:100:14
   2: alloc::vec::Vec<T,A>::remove::assert_failed
             at /home/ubuntu/tools/rmc/library/alloc/src/vec/mod.rs:1393:13
   3: alloc::vec::Vec<T,A>::remove
             at /home/ubuntu/tools/rmc/library/alloc/src/vec/mod.rs:1398:13
   4: rustc_codegen_rmc::codegen::intrinsic::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_intrinsic
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs:306:58
   5: <rustc_codegen_rmc::overrides::hooks::Intrinsic as rustc_codegen_rmc::overrides::hooks::GotocHook>::handle
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/overrides/hooks.rs:266:21
   6: rustc_codegen_rmc::codegen::statement::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_funcall
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/statement.rs:336:28
   7: rustc_codegen_rmc::codegen::statement::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_terminator
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/statement.rs:71:17
   8: rustc_codegen_rmc::codegen::block::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_block
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/block.rs:30:28
   9: rustc_codegen_rmc::codegen::function::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:99:71
  10: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:734:29
  11: core::iter::adapters::map::map_fold::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/map.rs:84:21
  12: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/enumerate.rs:106:27
  13: core::iter::traits::iterator::Iterator::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:2171:21
  14: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/enumerate.rs:112:9
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/map.rs:124:9
  16: core::iter::traits::iterator::Iterator::for_each
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:737:9
  17: rustc_codegen_rmc::codegen::function::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:99:13
  18: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:104:35
  19: rustc_codegen_rmc::utils::debug::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:87:13
  20: std::thread::local::LocalKey<T>::try_with
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:399:16
  21: std::thread::local::LocalKey<T>::with
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:375:9
  22: rustc_codegen_rmc::utils::debug::<impl rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:84:9
  23: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:103:25
  24: rustc_interface::passes::start_codegen::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1056:9
  25: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /home/ubuntu/tools/rmc/compiler/rustc_data_structures/src/profiling.rs:611:9
  26: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /home/ubuntu/tools/rmc/compiler/rustc_session/src/utils.rs:16:9
  27: rustc_interface::passes::start_codegen
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1055:19
  28: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:254:20
  29: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:784:42
  30: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1760:50
  31: rustc_middle::ty::context::tls::set_tlv
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1744:9
  32: rustc_middle::ty::context::tls::enter_context
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1760:9
  33: rustc_interface::passes::QueryContext::enter
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:784:9
  34: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:245:13
  35: rustc_interface::queries::Query<T>::compute
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:38:28
  36: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:407:13
  37: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:394:19
  38: rustc_driver::run_compiler::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:312:22
  39: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:203:13
  40: rustc_span::with_source_map
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:976:5
  41: rustc_interface::interface::create_compiler_and_run
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:197:5
  42: rustc_interface::interface::run_compiler::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:219:12
  43: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:145:13
  44: scoped_tls::ScopedKey<T>::set
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  45: rustc_span::create_session_globals_then
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:109:5
  46: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:143:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z trim-diagnostic-paths=no -Z codegen-backend=gotoc -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

[RMC] current codegen item: codegen_function: std::hint::black_box
_ZN4core4hint9black_box17h6d4673120023aca8E
[RMC] current codegen location: Loc { file: "/home/ubuntu/tools/rmc/library/core/src/hint.rs", function: None, line: 157, col: Some(1) }

RMC unexpectedly panicked during code generation.

If you are seeing this message, please file an issue here instead of on the Rust compiler: https://github.com/model-checking/rmc/issues/new?labels=bug&template=bug_report.md
error: could not compile `foo`
```

**Comment by zhassan-aws** [comment]
The steps above no longer result in a panic. Instead, they result in the following error:
```
     Running unittests (target/x86_64-unknown-linux-gnu/debug/deps/libfoo-43614fd88c70bcf2.rlib)
error: test failed, to rerun pass '--lib'

Caused by:
  could not execute process `/home/ubuntu/examples/iss586-2/foo/target/x86_64-unknown-linux-gnu/debug/deps/libfoo-43614fd88c70bcf2.rlib` (never executed)
```
which is encountered when `cargo test` tries to run the binary that calls the tests, which obviously RMC does not produce. The workaround is to specify the `--no-run` option to `cargo test` to prevent it from trying to run the non-existing binary:
```
RUSTFLAGS=$(rmc-rustc --rmc-flags) RUSTC=$(rmc-rustc --rmc-path) cargo test --no-run --target x86_64-unknown-linux-gnu -j1
```
One can then proceed with converting the symbol tables to goto binaries, linking them, and running CBMC.

**Comment by celinval** [comment]
@zhassan-aws can you please update the issue to reflect what you expect? From our offline discussions, I'm assuming that you want an option for `cargo rmc` to allow the user to pass a test function as a proof entry point. Correct?

**Comment by zhassan-aws** [comment]
Correct. We can close this issue though and create a separate feature request for `cargo rmc`.

**Comment by zhassan-aws** [comment]
With #672, `cargo rmc` now supports a `--tests` option. Closing this issue.
