### ISSUE TITLE
Panic with message "Error in struct_expr; value type does not match field type."

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/rmc#678]
I tried this code:

```rust
fn h(x: u8, y: usize, o: Option<std::num::NonZeroUsize>) {}

struct Foo {}

impl Foo {
    fn f(&self) {
        self.g(h)
    }
    fn g<F: Fn(u8, usize, Option<std::num::NonZeroUsize>)>(&self, ff: F) {
        ff(5, 22, None);
    }
}

fn main() {
    let x = Foo {};
    x.f();
}
```

using the following command line invocation:

```
rmc test.rs
```

with RMC version: `7d0d4cfc6da`

I expected to see this happen: Verification Successful

Instead, this happened:
```
thread 'rustc' panicked at 'Error in struct_expr; value type does not match field type.
        StructTag("tag-_10106284603884100227")
        [Field { name: "1", typ: CInteger(SizeT) }, Field { name: "0", typ: Unsignedbv { width: 8 } }, Field { name: "2", typ: StructTag("tag-_10110582897453494723") }]
        [Expr { value: Symbol { identifier: "_RNvYNvCs8ZdcvQGSn7l_4test1hINtNtNtCs61cxoXOqFbB_4core3ops8function2FnThjINtNtBw_6option6OptionNtNtNtBw_3num7nonzero12NonZeroUsizeEEE4callB4_::1::spread_2" }, typ: Unsignedbv { width: 8 }, location: None }, Expr { value: Symbol { identifier: "_RNvYNvCs8ZdcvQGSn7l_4test1hINtNtNtCs61cxoXOqFbB_4core3ops8function2FnThjINtNtBw_6option6OptionNtNtNtBw_3num7nonzero12NonZeroUsizeEEE4callB4_::1::spread_3" }, typ: CInteger(SizeT), location: None }, Expr { value: Symbol { identifier: "_RNvYNvCs8ZdcvQGSn7l_4test1hINtNtNtCs61cxoXOqFbB_4core3ops8function2FnThjINtNtBw_6option6OptionNtNtNtBw_3num7nonzero12NonZeroUsizeEEE4callB4_::1::spread_4" }, typ: StructTag("tag-_10110582897453494723"), location: None }]', compiler/cbmc/src/goto_program/expr.rs:716:9
stack backtrace:
   0: rust_begin_unwind
             at /home/ubuntu/tools/rmc/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /home/ubuntu/tools/rmc/library/core/src/panicking.rs:107:14
   2: <cbmc::goto_program::expr::Expr>::struct_expr_from_values
             at /home/ubuntu/tools/rmc/compiler/cbmc/src/goto_program/expr.rs:716:9
   3: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function_prelude
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:182:26
   4: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::codegen_function
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:92:13
   5: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:109:35
   6: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:87:13
   7: <std::thread::local::LocalKey<core::cell::RefCell<(core::option::Option<alloc::string::String>, core::option::Option<cbmc::goto_program::location::Location>)>>>::try_with::<<rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}>::{closure#0}, ()>
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:399:16
   8: <std::thread::local::LocalKey<core::cell::RefCell<(core::option::Option<alloc::string::String>, core::option::Option<cbmc::goto_program::location::Location>)>>>::with::<<rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}>::{closure#0}, ()>
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:375:9
   9: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#2}>
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:84:9
  10: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:108:25
  11: rustc_interface::passes::start_codegen::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1077:9
  12: <rustc_data_structures::profiling::VerboseTimingGuard>::run::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_data_structures/src/profiling.rs:644:9
  13: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_session/src/utils.rs:16:9
  14: rustc_interface::passes::start_codegen
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1076:19
  15: <rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:254:20
  16: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:805:42
  17: rustc_middle::ty::context::tls::enter_context::<<rustc_interface::passes::QueryContext>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1778:50
  18: rustc_middle::ty::context::tls::set_tlv::<rustc_middle::ty::context::tls::enter_context<<rustc_interface::passes::QueryContext>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1762:9
  19: rustc_middle::ty::context::tls::enter_context::<<rustc_interface::passes::QueryContext>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1778:9
  20: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:805:9
  21: <rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:245:13
  22: <rustc_interface::queries::Query<alloc::boxed::Box<dyn core::any::Any>>>::compute::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:38:28
  23: rustc_driver::run_compiler::{closure#1}::{closure#2}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:409:13
  24: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:394:19
  25: rustc_driver::run_compiler::{closure#1}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:314:22
  26: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:220:13
  27: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:971:5
  28: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:214:5
  29: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:236:12
  30: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:145:13
  31: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  32: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:109:5
  33: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:143:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z codegen-backend=gotoc -Z trim-diagnostic-paths=no -Z human_readable_cgu_names -Z symbol-mangling-version=v0 -Z symbol_table_passes= -Z human_readable_cgu_names -C overflow-checks=on

query stack during panic:
end of query stack

[RMC] current codegen item: codegen_function: std::ops::Fn::call
_RNvYNvCs8ZdcvQGSn7l_4test1hINtNtNtCs61cxoXOqFbB_4core3ops8function2FnThjINtNtBw_6option6OptionNtNtNtBw_3num7nonzero12NonZeroUsizeEEE4callB4_
[RMC] current codegen location: Loc { file: "/home/ubuntu/tools/rmc/library/core/src/ops/function.rs", function: None, line: 70, col: Some(5) }

RMC unexpectedly panicked during code generation.
```

**Comment by zhassan-aws** [comment]
Possible duplicate of #560.
